// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class x2_writer_edit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(x2_writer_edit));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181903539_x2_writer_edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
